# version: "3.9" # docker compose version

services:
  db: 
    image: postgres
    restart: always 
    environment:
      POSTGRES_USER: vl
      POSTGRES_PASSWORD: 123admin
      POSTGRES_DB: llocked
    ports:
      - 5432:5432 # Mapping ports: "port-on-machine":"port-on-container"
  adminer:
    image: adminer
    restart: always 
    environment:
      ADMINER_DESIGN: dracula # Pick a theme - https://github.com/vrana/adminer/tree/master/designs
    ports:
      - 3333:8080